# Generated by Django 3.1.4 on 2020-12-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=100)),
                ('is_normal_user', models.BooleanField(default=False)),
                ('is_nursery_user', models.BooleanField(default=False)),
            ],
        ),
    ]
