# Generated by Django 3.1.4 on 2020-12-16 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_auto_20201216_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='plant_images'),
        ),
    ]
